apiVersion: v1
kind: Service
metadata:
  name:  {{.Volumes.serverService.name}}
spec:
  type: {{.Volumes.serverService.type}}
  selector:
    component: web
  ports:
    - port: {{.Volumes.serverService.port}}
      targetPort: {{.Volumes.serverService.targetPort}}

