apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Volumes.serverDeployment.name}}
spec:
  replicas: {{.Volumes.serverDeployment.replicas}}
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image:  {{.Volumes.serverDeployment.image}}
          ports:
            - containerPort:  {{.Volumes.serverDeployment.containerPort}}
          env:
            - name: HOST
              value: mongodb-service
            - name: PORT
              value: "27017"
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongopassword
                  key: MONGOPASSWORD
